### ISSUE TITLE
boot hangs starting ntpd if no network cable

### ISSUE THREAD

**Issue by terrillmoore** [IthacaThings/ttn-multitech-cm#87] opened 2022-05-14 22:51 UTC
When running a gateway with cellular only (mlinux 5.3.31) and no network cable attached, boot hangs during ntp startup.

The first problem is that ppp needs to be started before ntp; the default mlinux config starts it *after* ntp.

The second problem is that there's a race condition; ppp needs to be started well before ntp so that the ppp interface is visible during ntp startup. 

Finally, when ppp comes up, the udhcpc scripts should be executed so that the appropriate services get started. (It seems that there might be a race condition between multiple interfaces coming up; not clear that we can coordinate with the Ethernet subsystem. However, if *no* cable is attached, things ought to work.)

**Comment by jchonig** [comment] 2022-09-20 21:50
Duplicate of https://github.com/IthacaThings/ttn-multitech-cm/issues/91

**Closed by jchonig** 2022-09-20 21:50 UTC
Labels: bug
